# configuration for "master" branch
-
  branches:
    only:
      - master
  configuration: Release
  before_build:
    - ps: nuget restore .\src\SImpl.NanoContainer.sln
  build:
    publish_nuget: true
    project: .\src\SImpl.NanoContainer.sln

  deploy:
    provider: NuGet
    api_key:
      secure: xSeMtJaoMJKZyuGmD3OlFCE2SNQ9y0O0qPToyL8JRCeRlDz1G8FwqLs5/oERnvog
    skip_symbols: false
    artifact: /.*(\.|\.s)nupkg/
