# configuration for "master" branch
-
  branches:
    only:
      - master
  configuration: Release
  before_build:
    - ps: nuget restore .\src\SImpl.NanoContainer.sln
  build:
    project: .\src\SImpl.NanoContainer.sln